package order

import (
	"strconv"
	"time"
)

type Order struct {
	ID              string    `json:"id"`
	ClientID        string    `json:"clientId"`
	AccountID       string    `json:"accountId"`
	Market          string    `json:"market"`
	Side            string    `json:"side"`
	Price           string    `json:"price"`
	TriggerPrice    string    `json:"triggerPrice"`
	TrailingPercent string    `json:"trailingPercent"`
	Size            string    `json:"size"`
	RemainingSize   string    `json:"remainingSize"`
	Type            string    `json:"type"`
	UnfillableAt    string    `json:"unfillableAt"`
	Status          string    `json:"status"`
	TimeInForce     string    `json:"timeInForce"`
	CancelReason    string    `json:"cancelReason"`
	PostOnly        bool      `json:"postOnly"`
	CreatedAt       time.Time `json:"createdAt"`
	ExpiresAt       time.Time `json:"expiresAt"`
}

func (o Order) Pri() float32 {
	f, e := strconv.ParseFloat(o.Price, 32)
	if e != nil {
		panic(e)
	}

	return float32(f)
}

func (o Order) Rem() float32 {
	f, e := strconv.ParseFloat(o.RemainingSize, 32)
	if e != nil {
		panic(e)
	}

	return float32(f)
}

func (o Order) Siz() float32 {
	f, e := strconv.ParseFloat(o.Size, 32)
	if e != nil {
		panic(e)
	}

	return float32(f)
}

//

type CancelRequest struct {
	// ID specifies the Order to cancel. If ID is empty, all orders will be
	// cancelled.
	ID string `json:"id"`
}

//

type CreateRequest struct {
	Position        int64     `json:"-"`
	Market          string    `json:"market"`
	Side            string    `json:"side"`
	Type            string    `json:"type"`
	PostOnly        bool      `json:"postOnly"`
	Size            string    `json:"size"`
	Price           string    `json:"price"`
	LimitFee        string    `json:"limitFee"`
	Expiration      time.Time `json:"expiration"`
	TimeInForce     string    `json:"timeInForce"`
	CancelId        string    `json:"cancelId,omitempty"`
	TriggerPrice    string    `json:"triggerPrice,omitempty"`
	TrailingPercent string    `json:"trailingPercent,omitempty"`
	ReduceOnly      bool      `json:"reduceOnly"`
	ClientId        string    `json:"clientId"`
	// Signature will be generated by the client before sending the HTTP Post
	// request to the configured API endpoint.
	Signature string `json:"signature"`
}

type CreateResponse struct {
	Order Order `json:"order"`
}

//

type GetRequest struct {
	ID string `json:"id"`
}

type GetResponse struct {
	Order Order `json:"order"`
}

//

type ListRequest struct {
	Limit              int       `json:"limit"`
	Market             string    `json:"market"`
	Status             string    `json:"status"`
	Type               string    `json:"type"`
	Side               string    `json:"side"`
	CreatedBeforeOrAt  time.Time `json:"createdAt"`
	ReturnLatestOrders bool      `json:"returnLatestOrders"`
}

type ListResponse struct {
	Orders Orders `json:"orders"`
}
